name: Create comment on new issue

on:
  issues:
    types: [opened]
    
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
    
  comment-with-api:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/Ben-Costa/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='Me too'" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
